### ISSUE TITLE
Power value not inverting

### ISSUE THREAD

**Issue by clomads** [latonita/esphome-ina228#1]
First of all thank you so much for building this. I've been working on hardware since last summer and I'm not much of a developer. I was looking to get someone to help me finish the work I had a friend do back then and decided to double check github and here this is. Wonderful work, and I think i'm gonna move from the INA237 to the INA238 in my next prototype.

Anyways, I'm getting great results so far, but the power value doesn't go negative when running in reverse, but shuntV and current do. I've included a screenshot.
<img width="316" alt="Screenshot 2024-02-12 at 8 01 58 AM" src="https://github.com/latonita/esphome-ina228/assets/1334775/e9387cd4-ebc0-4613-bac8-30712f6cf4e9">

**Comment by latonita** [comment]
Hi.
Power can't become negative) if voltage is negative and current is negative, then P=UI it becomes positive)

BR, Anton
________________________________
From: Chloe Madison-Ryan ***@***.***>
Sent: Monday, February 12, 2024 5:50:12 PM
To: latonita/esphome-ina228 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [latonita/esphome-ina228] Power value not inverting (Issue #1)


First of all thank you so much for building this. I've been working on hardware since last summer and I'm not much of a developer. I was looking to get someone to help me finish the work I had a friend do back then and decided to double check github and here this is. Wonderful work, and I think i'm gonna move from the INA237 to the INA238 in my next prototype.

Anyways, I'm getting great results so far, but the power value doesn't go negative when running in reverse, but shuntV and current do. I've included a screenshot.
Screenshot.2024-02-12.at.8.01.58.AM.png (view on web)<https://github.com/latonita/esphome-ina228/assets/1334775/e9387cd4-ebc0-4613-bac8-30712f6cf4e9>

**Comment by clomads** [comment]
bus voltage is still positive and that should be what it should be calculated against. in this case:

25.69687v * -17.13562012i = -440.331802593w

shunt voltage is just a reference to calculate current. if current is negative power should be negative, no?

**Comment by kolins-cz** [comment]
I believe there should be negative power. At least as an option. In solar power applications, negative current and power usually means discharging battery. 

Naturally, you can't have power loss of -50W on resistor. But for me it would mean that power flows in opposite way.

Author of this component dealt with this topic like this:

![image](https://github.com/latonita/esphome-ina228/assets/8409715/9f9d3d5c-2cd9-4e6a-a604-8a200929a9ca)

https://github.com/syssi/esphome-jbd-bms

BMS Power is +-
Charging and discharging power is always positive

**Comment by latonita** [comment]
Okay, I was too fast in judgment.
As per datasheet this value is always positive.

"Calculated power output.
Output value in watts.
Unsigned representation. Positive value"

If you need negative sign you might use custom filter to multiply it by - 1 when needed

BR, Anton
________________________________

**Comment by clomads** [comment]
Fair enough, that should be no problem. Thanks for your help and thanks again for building this.

**Comment by latonita** [comment]
@kolins-cz @clomads hi, can you test last version on esphome PR 
https://github.com/esphome/feature-requests/issues/2549 ?
i would be very thankful

**Comment by clomads** [comment]
hey @latonita this is working well at first look but the new required "model" entry is a bit confusing and I couldn't find any updated docs for it. When I use INA238, which the compiler seems happy with, the chip returns "238" which throws an error, but it still works. Changing to 238 or "238" it throws an error and doesn't compile.

<img width="426" alt="Screenshot 2024-05-13 at 3 02 42 PM" src="https://github.com/latonita/esphome-ina228/assets/1334775/ba427912-b1f1-4126-bf09-171bf0d030a9">

<img width="896" alt="Screenshot 2024-05-13 at 2 33 23 PM" src="https://github.com/latonita/esphome-ina228/assets/1334775/28627842-65b1-4572-8dd3-0b031d11fecd">

also, just wanted to mention while I'm here that I got accepted by Crowd Supply to do a funding campaign on my 500A shunt that I'll be releasing with your component. I truly appreciate the work you've done here. In case you wanna take a look, here's my docs so far: https://wiki.vdbx.io/products/pwrtool500

**Comment by latonita** [comment]
@clomads thanks for testing, apologies, i forgot to update docs. model shall be 'INA228' or other INA238 or. ... etc.

Great to hear about your progress! Keep up doing things!

**Comment by latonita** [comment]
@clomads and thats good idea to use just 238 instead of INA238, i will add it as well

**Comment by latonita** [comment]
@clomads can I have a full log with level = verbose  please?
my device is no longer with me , need to check 
thanks

**Comment by latonita** [comment]
> hey @latonita this is working well at first look but the new required "model" entry is a bit confusing and I couldn't find any updated docs for it. When I use INA238, which the compiler seems happy with, the chip returns "238" which throws an error, but it still works.
i think i found this minor glitch and fixed it. check latest ver.

**Comment by clomads** [comment]
Hey @latonita it's perfect! 
<img width="571" alt="Screenshot 2024-05-14 at 1 56 57 PM" src="https://github.com/latonita/esphome-ina228/assets/1334775/0ea84b05-1d26-4da8-92eb-39d615278785">

**Comment by kolins-cz** [comment]
> @kolins-cz @clomads hi, can you test last version on esphome PR [esphome/feature-requests#2549](https://github.com/esphome/feature-requests/issues/2549) ? i would be very thankful

Hello,
I have tested some version, hopefully the latest. 
```
external_components:
  - source: github://syssi/esphome-jk-bms@main
  - source: github://syssi/esphome-jbd-bms@main
  - source: github://pr#6138
    components: [ina2xx_base, ina2xx_spi]
    refresh: 0s
```

I have added `model: INA229` and everything seems to be working like before

I am still confused about what PR# to use from where and how. Let me know if I used wrong one.
